version: "3"
services:
  app:
    image: react-redux-homework_app
    container_name: app
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"